<a href="https://colab.research.google.com/github/MHRDYN7/Tensorflow-Keras/blob/main/Tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [2]:
"""
tf.constant(value, dtype=None, shape=None, name='Const')
"""

x = tf.constant(4, shape=(1, 1), dtype=tf.float32)
print(x)

x = tf.constant([[1, 2, 3], [4, 5, 6]], shape=(2, 3))
print(x)

"""
tf.eye(num_rows, num_columns=None, batch_shape=None, dtype=tf.dtypes.float32, name=None)
"""
x = tf.eye(3)
print(x)

x = tf.ones((4, 3))
print(x)

x = tf.zeros((3, 2, 5))
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 2, 5), dtype=float32)


In [5]:
x = tf.random.uniform((2, 2), minval=0, maxval=1)
print(x)

x = tf.random.normal((3, 3), mean=0, stddev=1)
print(tf.cast(x, dtype=tf.float64))
# tf.cast is used for changing the data type

tf.Tensor(
[[0.00276923 0.08802152]
 [0.9592235  0.08349288]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.34456208 -0.68735921  0.79477817]
 [ 1.23752153 -1.36579514  0.10745967]
 [ 1.8117938   0.41304871 -0.16240966]], shape=(3, 3), dtype=float64)


In [6]:
x = tf.range(9)
print(x)
x = tf.range(start=0, limit=10, delta=2)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


In [7]:
#Simple math operations work element wise
#tf.tensordot(x, y, axes=1)
#tf.matmul(x,y)

In [8]:
#to do
#most of the common indexing rules apply, but check x[::2]
#investigate tf.gather()
#Completely understand the notion behind tf.reshape(x, (3, 3)) and tf.transpose(x, perm=[1, 0])